template = ""
rev_id = 243
template_sha = "282e395615378764f981aafc0230e12ffd633e48"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
