template = ""
rev_id = 239
template_sha = "0ad4d24907fe48e56692e2c8d2ac749fd207326c"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
