template = ""
rev_id = 256
template_sha = "4e2ddf168a2aaf68d2c29db9e79e44e1dc4c2b76"

[replacements]
__GLOTTOLOG_ID__ = "temb1276"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
