template = ""
rev_id = 254
template_sha = "9eb2a95995f59cb63a159a5cc7bcce8f049babe4"

[replacements]
__GLOTTOLOG_ID__ = "temb1276"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
