template = ""
rev_id = 242
template_sha = "375a5816b2c9ca7056bc78fc11a9adc792f69faf"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
