template = ""
rev_id = 250
template_sha = "fc3ee4b759f7e4d74e61feb6577fcefe25384f4a"

[replacements]
__GLOTTOLOG_ID__ = "temb1276"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
