template = ""
rev_id = 245
template_sha = "6264a1351c6fd30e2a0f34d7ece4150965d960d8"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
