template = ""
rev_id = 281
template_sha = "818353eecbfc8e1309992f6739dfde72a0afbec0"

[replacements]
__GLOTTOLOG_ID__ = "temb1276"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
