template = ""
rev_id = 272
template_sha = "f40ff07ea2383e4e83e8ad0ff88b795ceaf841e6"

[replacements]
__GLOTTOLOG_ID__ = "temb1276"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
