template = ""
rev_id = 268
template_sha = "444a55f5c0c0489e8f1dcde2639b74c44c24dffb"

[replacements]
__GLOTTOLOG_ID__ = "temb1276"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
