template = ""
rev_id = 260
template_sha = "2e95e152f66f76c7c7a22b2f9d91adbb75b07d95"

[replacements]
__GLOTTOLOG_ID__ = "temb1276"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
