template = ""
rev_id = 253
template_sha = "7b8a6c39a9307995ad9926ecd5b777ca888b3659"

[replacements]
__GLOTTOLOG_ID__ = "temb1276"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
