template = ""
rev_id = 223
template_sha = "f4ae0ba4a15c7ca7b0dbbb23cdf12355758920b4"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Temb√©"
__UND__ = "tqb"
